"""Generate GARCH golden fixtures for the Go port.

Implements the GJR-GARCH(1,1,1) forward-variance recursion INDEPENDENTLY of the
Go code (docs/_verify/garch_model_clean.py is the lineage: its analytic forecast
was verified against the `arch` library to six decimals) and persists the
expected sigma-bar(T) values as JSON. The Go test
(internal/garch/golden_test.go) pins SigmaBarT to these numbers at 1e-12 rel.

Recursion (decimal daily units):

    h_1 = omega + (alpha + gamma*1{eps0<0})*eps0^2 + beta*h0
    h_k = omega + (alpha + gamma/2 + beta)*h_{k-1},  k >= 2
    sigma_bar(T) = sqrt(252/T * sum_{k=1..T} h_k)

CONVENTION PINNED HERE: T is the day count the caller supplies — the Go engine
passes calendar DTE from Contract.DTE (calendar-day proxy; trading-day calendars
arrive with the fit job). The horizons below are recursion step counts, nothing
else. A zero/negative h0 warm-starts at the unconditional variance
omega/(1-persistence), mirroring SigmaBarT.

Run:  python docs/_verify/generate_garch_goldens.py
Writes: core/internal/garch/testdata/garch_golden.json
"""
import json
import math
import os

HORIZONS = [1, 7, 14, 30, 90]


def sigma_bar_t(omega, alpha, gamma, beta, h0, eps, days):
    if not (h0 > 0) or math.isnan(h0) or math.isinf(h0):
        h0 = omega / (1.0 - (alpha + gamma / 2.0 + beta))
    neg = 1.0 if eps < 0 else 0.0
    h = omega + (alpha + gamma * neg) * eps * eps + beta * h0
    total = h
    coef = alpha + gamma / 2.0 + beta
    for _ in range(days - 1):
        h = omega + coef * h
        total += h
    return math.sqrt(252.0 * total / days)


CASES = [
    # name, omega, alpha, gamma, beta, last_h, last_eps
    ("baseline-negative-shock", 2e-6, 0.08, 0.06, 0.86, 1e-4, -0.011),
    ("positive-shock-no-leverage", 2e-6, 0.08, 0.06, 0.86, 1e-4, 0.008),
    ("elevated-variance-state", 2e-6, 0.08, 0.06, 0.86, 4e-4, -0.03),
    ("zero-state-warm-start", 2e-6, 0.08, 0.06, 0.86, 0.0, 0.0),
    ("near-unit-persistence", 5e-7, 0.01, 0.01, 0.98, 9e-5, -0.02),
    ("calm-market", 1e-6, 0.05, 0.03, 0.90, 5e-5, 0.004),
]


def main():
    out = {
        "description": "GJR-GARCH(1,1,1) forward-variance sigma-bar(T) goldens, "
                       "decimal daily units, generated by docs/_verify/generate_garch_goldens.py",
        "day_convention": "horizons are the recursion step count exactly as supplied; "
                          "the Go engine passes calendar DTE (calendar-day proxy)",
        "annualization": "sqrt(252 * mean_variance)",
        "cases": [],
    }
    for name, omega, alpha, gamma, beta, h0, eps in CASES:
        case = {
            "name": name,
            "omega": omega, "alpha": alpha, "gamma": gamma, "beta": beta,
            "last_h": h0, "last_eps": eps,
            "sigma_bar": {str(t): sigma_bar_t(omega, alpha, gamma, beta, h0, eps, t)
                          for t in HORIZONS},
        }
        out["cases"].append(case)

    dest = os.path.join(os.path.dirname(__file__), os.pardir, os.pardir,
                        "core", "internal", "garch", "testdata", "garch_golden.json")
    dest = os.path.normpath(dest)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    print(f"wrote {dest}")
    for c in out["cases"]:
        print(f"  {c['name']}: " + "  ".join(
            f"T={t}={c['sigma_bar'][str(t)]:.6f}" for t in HORIZONS))


if __name__ == "__main__":
    main()
