package garch

import (
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

// Golden fixtures: expected sigma-bar(T) values at
// T ∈ {1,7,14,30,90} generated by the independent Python recursion in
// docs/_verify/generate_garch_goldens.py (lineage: garch_model_clean.py, which
// matched the `arch` library's analytic forecast to six decimals). The fixture
// also pins the day-count convention — horizons are the step count exactly as
// supplied, and the engine supplies calendar DTE.
type goldenFile struct {
	Description   string       `json:"description"`
	DayConvention string       `json:"day_convention"`
	Annualization string       `json:"annualization"`
	Cases         []goldenCase `json:"cases"`
}

type goldenCase struct {
	Name     string             `json:"name"`
	Omega    float64            `json:"omega"`
	Alpha    float64            `json:"alpha"`
	Gamma    float64            `json:"gamma"`
	Beta     float64            `json:"beta"`
	LastH    float64            `json:"last_h"`
	LastEps  float64            `json:"last_eps"`
	SigmaBar map[string]float64 `json:"sigma_bar"`
}

var goldenHorizons = []int{1, 7, 14, 30, 90}

func TestGoldenSigmaBarT(t *testing.T) {
	blob, err := os.ReadFile("testdata/garch_golden.json")
	if err != nil {
		t.Fatalf("reading golden fixture: %v", err)
	}
	var f goldenFile
	if err := json.Unmarshal(blob, &f); err != nil {
		t.Fatalf("parsing golden fixture: %v", err)
	}
	if f.Annualization != "sqrt(252 * mean_variance)" {
		t.Fatalf("fixture annualization convention changed: %q", f.Annualization)
	}
	if len(f.Cases) == 0 {
		t.Fatal("golden fixture has no cases")
	}
	for _, c := range f.Cases {
		p := Params{Ticker: "GOLDEN", Omega: c.Omega, Alpha: c.Alpha,
			GammaLeverage: c.Gamma, Beta: c.Beta}
		if err := p.Validate(); err != nil {
			t.Fatalf("%s: fixture params invalid: %v", c.Name, err)
		}
		s := State{LastH: c.LastH, LastEps: c.LastEps}
		for _, days := range goldenHorizons {
			want := c.SigmaBar[strconv.Itoa(days)]
			got, err := SigmaBarT(p, s, days)
			if err != nil {
				t.Fatalf("%s T=%d: %v", c.Name, days, err)
			}
			if d := relDiff(got, want); d > 1e-12 {
				t.Fatalf("%s T=%d: SigmaBarT = %.15g, golden %.15g (rel %.3g > 1e-12)",
					c.Name, days, got, want, d)
			}
		}
		// Model.SigmaBar must round calendar DTE to whole days and land on the
		// same golden value (the convention the engine's Contract.DTE feed
		// relies on).
		m, err := NewModel(p, s)
		if err != nil {
			t.Fatalf("%s: NewModel: %v", c.Name, err)
		}
		want14 := c.SigmaBar["14"]
		if d := relDiff(m.SigmaBar(13.5), want14); d > 1e-12 {
			t.Fatalf("%s: Model.SigmaBar(13.5) = %.15g, want T=14 golden %.15g", c.Name, m.SigmaBar(13.5), want14)
		}
		if d := relDiff(m.SigmaBar(14.49), want14); d > 1e-12 {
			t.Fatalf("%s: Model.SigmaBar(14.49) = %.15g, want T=14 golden %.15g", c.Name, m.SigmaBar(14.49), want14)
		}
	}
}
